CREATE TABLE USERS
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	MAIL VARCHAR(255) NOT NULL,
	USERNAME NVARCHAR(255) NOT NULL,
	PASSWORD NVARCHAR(255) NOT NULL,
	CONSTRAINT PK_USER_ID PRIMARY KEY(ID)
);

CREATE TABLE COURSES
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255),
	CATEGORY NVARCHAR(255),
	CONSTRAINT PK_COURSE_ID PRIMARY KEY(ID)
);

CREATE TABLE TOPICS
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	TITLE NVARCHAR(255) NOT NULL,
	MESSAGE NVARCHAR(2147483647) NOT NULL,
	ID_COURSE BIGINT NOT NULL,
	CREATED DATETIME,
	STATUS NVARCHAR(255) NOT NULL,
	ID_AUTHOR BIGINT NOT NULL,
	CONSTRAINT PK_TOPIC_ID PRIMARY KEY(ID),
	CONSTRAINT FK_COURSE_ID FOREIGN KEY(ID_COURSE) REFERENCES COURSES(ID),
	CONSTRAINT FK_AUTHOR_ID FOREIGN KEY(ID_AUTHOR) REFERENCES USERS(ID)
);

CREATE TABLE ANSWERS
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	MESSAGE NVARCHAR(2147483647) NOT NULL,
	ID_TOPIC BIGINT NOT NULL,
	CREATED DATETIME NOT NULL,
	SOLUTION BOOLEAN,
	CONSTRAINT PK_ANSWER_ID PRIMARY KEY(ID),
	CONSTRAINT FK_TOPIC_ID FOREIGN KEY(ID_TOPIC) REFERENCES TOPICS(ID)
);